// Client-side SIMULATED data for the M-R BINARY demo.
// NOTHING here predicts real markets. All numbers are random walks for UI demo only.

import type { MarketPriceData, SignalResponse, PhaseCheck, TimeFrameOption } from "./types";

const BASE_PRICES: Record<string, number> = {
  "XAU/USD": 2378.45,
  "BTC/USD": 67250.0,
  "USD/JPY": 157.42,
  "EUR/USD": 1.0824,
  "GBP/USD": 1.2715,
};

const priceState: Record<string, { price: number; high: number; low: number; opened: number }> = {};

function getState(pair: string) {
  if (!priceState[pair]) {
    const base = BASE_PRICES[pair] ?? 100;
    priceState[pair] = { price: base, high: base, low: base, opened: base };
  }
  return priceState[pair];
}

function decimals(pair: string) {
  return pair.includes("EUR") || pair.includes("GBP") ? 5 : 2;
}

function driftScale(pair: string) {
  if (pair.includes("BTC")) return 15.0;
  if (pair.includes("JPY")) return 0.05;
  if (pair.includes("EUR") || pair.includes("GBP")) return 0.00008;
  return 0.08;
}

export async function simulateMarketData(pair: string): Promise<MarketPriceData> {
  const s = getState(pair);
  const d = decimals(pair);
  const prev = s.price;
  const next = parseFloat((prev + (Math.random() - 0.5) * driftScale(pair)).toFixed(d));
  s.price = next;
  if (next > s.high) s.high = next;
  if (next < s.low) s.low = next;
  return {
    success: true,
    source: "SIMULATED_DEMO",
    pair,
    price: next,
    change: parseFloat((((next - s.opened) / s.opened) * 100).toFixed(4)),
    high: parseFloat(s.high.toFixed(d)),
    low: parseFloat(s.low.toFixed(d)),
    timestamp: Date.now(),
  };
}

const PHASE_INDICATORS = [
  "PHASE 1: SCANNING REAL-TIME MARKET & PRICE MOVEMENTS...",
  "PHASE 2: ANALYZING TECHNICAL INDICATORS & CHART PATTERNS..",
  "PHASE 3: PROCESSING AI ALGORITHM FOR TREND PREDICTION...",
  "PHASE 4: EVALUATING SUPPORT AND RESISTANCE LEVELS...",
  "PHASE 5: COMPUTING OPTIMAL ENTRY POINTS & MARKET SENTIMENT..",
  "PHASE 6: FINALIZING SIMULATED CONFIDENCE MATRICES...",
];

export async function simulateSignal(
  pair: string,
  timeFrame: TimeFrameOption,
  allowWaitSignal: boolean,
): Promise<SignalResponse> {
  const s = getState(pair);
  const d = decimals(pair);
  const r = Math.random();
  let direction: "CALL" | "PUT" | "WAIT";
  if (allowWaitSignal && r < 0.15) direction = "WAIT";
  else direction = r < 0.575 ? "CALL" : "PUT";

  const isUp = direction === "CALL";
  const isWait = direction === "WAIT";

  let slOffset = 4.5, tp1 = 3.2, tp2 = 6.8, tp3 = 11.45;
  if (pair === "EUR/USD" || pair === "GBP/USD") { slOffset = 0.0035; tp1 = 0.0022; tp2 = 0.0048; tp3 = 0.0085; }
  else if (pair === "USD/JPY") { slOffset = 0.45; tp1 = 0.32; tp2 = 0.68; tp3 = 1.15; }
  else if (pair === "BTC/USD") { slOffset = 350; tp1 = 250; tp2 = 550; tp3 = 950; }

  const entryPrice = parseFloat(s.price.toFixed(d));
  const stopLossPrice = parseFloat((isUp ? s.price - slOffset : s.price + slOffset).toFixed(d));
  const tp1Price = parseFloat((isUp ? s.price + tp1 : s.price - tp1).toFixed(d));
  const tp2Price = parseFloat((isUp ? s.price + tp2 : s.price - tp2).toFixed(d));
  const tp3Price = parseFloat((isUp ? s.price + tp3 : s.price - tp3).toFixed(d));

  // SIMULATED confidence — for demo visuals only.
  const accuracy = parseFloat((60 + Math.random() * 20).toFixed(2));

  const phases: PhaseCheck[] = PHASE_INDICATORS.map((indicator, i) => ({
    phase: i + 1,
    indicator,
    accuracy: 90 + Math.floor(Math.random() * 10),
    status: "SIMULATED",
    passed: true,
  }));

  const drivers = isWait
    ? [
        `${pair} is in simulated sideways compression. (demo data)`,
        "Buyer/seller volumes balanced in this random sample. (demo)",
        "Moving averages flat in the random walk. (demo)",
        "RSI near 50 in this simulated sample. (demo)",
        "Demo: no real macro events analyzed.",
      ]
    : isUp
    ? [
        `Random walk slope positive for ${pair}. (demo)`,
        "Simulated RSI bounce from oversold. (demo)",
        "Demo: no real order flow analyzed.",
        "Demo: no real liquidity sweep detected.",
        "Simulated breakout pattern. (demo)",
      ]
    : [
        `Random walk slope negative for ${pair}. (demo)`,
        "Simulated overbought RSI. (demo)",
        "Demo: no real distribution detected.",
        "Demo: no real exhaustion pattern.",
        "Simulated breakdown. (demo)",
      ];

  return {
    success: true,
    pair,
    direction,
    timeFrame,
    priceAtSignal: entryPrice,
    accuracy,
    executeTime: new Date(Date.now() + 1500).toISOString().slice(11, 19) + " UTC",
    aiReasoning:
      "SIMULATED OUTPUT — this number was generated by a random walk for UI demo. Do not trade real money on this.",
    phases,
    timestamp: Date.now(),
    signalDecision: isWait ? "HOLD" : isUp ? "BUY" : "SELL",
    confidence: Math.round(accuracy),
    scantimeframe: "SIMULATED",
    entryPrice,
    stopLossPrice,
    tp1Price,
    tp2Price,
    tp3Price,
    rrRatio: "1:2.0 (demo)",
    top5Drivers: drivers,
    riskWarning: "DEMO ONLY. Do not trade real money on simulated signals.",
    invalidation: "Demo signal — no real invalidation criteria.",
  };
}
